### ISSUE TITLE
Hello~ How to get "ctc_detect_tags.txt"？

### ISSUE THREAD

**Issue by JieWu02** [GMago-LeWay/GECFramework#2]

**Comment by GMago-LeWay** [comment]
Hello, we had update README for the tag download.

https://drive.google.com/drive/folders/1GSYg1NX3BHOOGy-zyxelFkQZXocKzKLS?usp=sharing

**Comment by JieWu02** [comment]
> Hello, we had update README for the tag download.
> 
> https://drive.google.com/drive/folders/1GSYg1NX3BHOOGy-zyxelFkQZXocKzKLS?usp=sharing

Thanks, that is much clear.

best  regrads
